"""update jobs experience and skills

Revision ID: 280f686cbde7
Revises: 2ca9e4916cd9
Create Date: 2026-04-27 22:44:29.448275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '280f686cbde7'
down_revision = '2ca9e4916cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('experience_max')
        batch_op.drop_column('experience_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_min', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('experience_max', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('skills')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
